### ISSUE TITLE
Migrate to use of PostgreSQL database and database Views

### ISSUE THREAD

**Issue by shansen5** [edgi-govdata-archiving/ECHO-COVID19#40]

**Comment by shansen5** [comment]
This is ready in the postres_migrate branch.  (Note that this is the branch with the missing 'g' from postgres.  My typo.)  This branch shouldn't be merged with main until we are ready to commit to using the PostgreSQL database.

**Comment by ericnost** [comment]
This is looking good. I gave it a test run. A few issues:

1. Yes, we need to decide about using pg first. I think I am supportive of this.
2. The cell under 'Are facilities monitoring their air emissions?' needs to call from ICIS-AIR_STACK_TESTS
3. For testing, we just need to change the git call to drop the 'g' in the name of the branch (not an issue once we merge...)
4. The cell that begins
```
latest = air_data[(air_data["HPV_DAYZERO_DATE"] >= '2020')]

# Pull out Ids to match ECHO_EXPORTER
ids = latest.index.unique()
```
no longer works because latest's index is not the PGM_SYS_ID any more. Just need to specify PGM_SYS_ID as the column for the unique()
